window.TECHBUILD_CONFIG = {
  brandName: "TechBuild NG",
  whatsappNumber: "+491771371042",
  liveWebsiteUrl: "https://wizyt78.github.io/Elonmusk-Tesla/",
  videoVimeoUrl: "https://vimeo.com/1230761431",
  videoShowcase: [
    { title: "New Website Product Walkthrough", url: "https://vimeo.com/1230761431", label: "Website product demo" }
  ],
  currency: "NGN",
  korapayEnabled: true,
  apiBase: "",
  packages: {
  "stylehub": {
    "id": "stylehub",
    "salesCount": 66,
    "title": "STYLEHUB — Clothing & Online Store",
    "price": 149000,
    "oldPrice": 250000,
    "minDeposit": 100,
    "logo": "assets/clothing-store.svg",
    "cover": "assets/product-covers/stylehub-clothing-online-store-main.jpg",
    "tag": "NEW • Premium fashion store",
    "category": "Clothing & Online Store",
    "description": "A new premium ready-made fashion e-commerce website for selling men's and women's clothing, shoes, bags, and wrist watches.",
    "detailTitle": "STYLEHUB — Clothing & Online Store",
    "detailDescription": "A premium ready-made fashion e-commerce website with a polished storefront, product catalog, product details, cart and checkout, WhatsApp support, and a full admin dashboard for managing products, images, variants, inventory, orders, customers, promotions, and store settings.",
    "features": [
      "Premium Fashion Design",
      "Men & Women Products",
      "Cart & Checkout",
      "Admin Dashboard",
      "Product Management",
      "WhatsApp",
      "KoraPay Ready",
      "Mobile Responsive",
      "Cloudflare Ready"
    ]
  },
  "socialmedia": {
    "id": "socialmedia",
    "salesCount": 347,
    "title": "Buy All Social Media Accounts & Foreign Numbers Website",
    "price": 150000,
    "oldPrice": 200000,
    "minDeposit": 100000,
    "logo": "assets/social-media-store.svg",
    "cover": "assets/product-covers/socialmedia-website-main.jpg",
    "tag": "Marketplace website",
    "category": "Social Media & Foreign Number Marketplace",
    "description": "A ready-made marketplace website package where customers can create accounts, fund a wallet, browse available social media account listings and foreign phone-number products, and place orders. Includes an admin dashboard for managing customers, listings, prices, deposits, wallet balances, and orders.",
    "detailTitle": "Buy All Social Media Accounts & Foreign Numbers Website",
    "detailDescription": "A complete marketplace website package for a business offering eligible digital account-related products and foreign phone-number services. Customers can register and sign in, view their wallet balance, deposit funds, browse listings, purchase available products, and track orders. The admin dashboard is designed to manage users, product listings, prices, inventory, deposit records, wallet balances, and orders. Any account-related offerings must comply with applicable laws and the relevant service providers’ terms; use phone numbers only with proper authorization.",
    "features": [
      "Customer registration and secure login",
      "Customer wallet balance and deposit interface",
      "Marketplace listings for eligible account products and foreign numbers",
      "Purchase flow and customer order history",
      "Admin dashboard for users, listings, inventory, and pricing",
      "Admin tools for reviewing deposits, wallet records, and orders",
      "Responsive mobile and desktop layout"
    ]
  },
  "standard": {
    "id": "standard",
    "salesCount": 137,
    "title": "Tesla Investment Website",
    "price": 150000,
    "oldPrice": 250000,
    "minDeposit": 75000,
    "logo": "assets/tesla-investment-logo.svg",
    "cover": "assets/product-covers/standard-website-main.jpg",
    "tag": "Ready to customize",
    "category": "Investment Website",
    "description": "A professional investment website package with client registration, account dashboards, balance and earnings views, plus an admin dashboard for managing users and investment plans.",
    "detailTitle": "Tesla Investment Website",
    "detailDescription": "A ready-to-customize investment website foundation with client registration, secure sign-in, account dashboards, balance and earnings views, and a dedicated admin area for managing users, accounts, and investment plans. Confirm the final features and any compliance requirements before launch.",
    "features": [
      "Client registration and secure login",
      "Client balance and earnings views",
      "Admin dashboard and account management",
      "Investment plan management",
      "Responsive mobile and desktop layout",
      "Ready for branding and customization"
    ]
  },
  "custom": {
    "id": "custom",
    "salesCount": 26,
    "title": "Custom Investment Website",
    "price": 180000,
    "oldPrice": 300000,
    "minDeposit": 100000,
    "logo": "assets/custom-build-logo.svg",
    "cover": "assets/product-covers/custom-website-main.jpg",
    "tag": "Custom build",
    "category": "Investment Website",
    "description": "A customizable investment website foundation with client accounts, balance views, and an admin experience, tailored to your requested branding and features.",
    "detailTitle": "Custom Investment Website",
    "detailDescription": "Start with a professional investment website foundation and tailor its branding, pages, and agreed features. The package can include client accounts, balance views, investment plan presentation, and an admin experience. Confirm functionality and applicable financial-service requirements before launch.",
    "features": [
      "Client registration and secure login",
      "Client account and balance views",
      "Admin dashboard and user management",
      "Investment plan presentation",
      "Branding and page customization",
      "Responsive mobile and desktop layout"
    ]
  },
  "banking": {
    "id": "banking",
    "salesCount": 43,
    "title": "Banking Website with Admin Dashboard",
    "price": 180000,
    "oldPrice": 350000,
    "minDeposit": 100000,
    "logo": "assets/banking-website.svg",
    "cover": "assets/product-covers/banking-website-main.jpg",
    "tag": "Banking platform",
    "category": "Banking Website",
    "description": "A professional banking-style website package with customer account pages, balance and transaction views, and an admin dashboard for managing customer records and site content.",
    "detailTitle": "Banking Website with Admin Dashboard",
    "detailDescription": "A banking-style web platform designed around customer registration, account dashboards, balance and transaction-history views, and an admin area for managing customer records and website content. This is a website build, not a licensed banking service or a payment institution.",
    "features": [
      "Customer registration and login pages",
      "Account dashboard and balance display",
      "Transaction-history interface",
      "Admin dashboard and customer management",
      "Editable banking-style pages and branding",
      "Responsive mobile and desktop layout"
    ]
  },
  "loanbanking": {
    "id": "loanbanking",
    "salesCount": 86,
    "title": "Premium Loan & Banking Website",
    "price": 200000,
    "oldPrice": 350000,
    "minDeposit": 100000,
    "logo": "assets/banking-website.svg",
    "cover": "assets/product-covers/loan-banking-website-main.jpg",
    "tag": "Premium loan platform",
    "category": "Loan & Banking Website",
    "description": "A premium loan and banking website package with a polished landing page, mobile-responsive customer account, loan application flow, customer dashboard, loan and payment history, and a full admin management experience. The admin concept supports manual loan approval/rejection, manual funding or debit/credit adjustments in the currencies configured by the site owner, customer management, messaging, account suspension/deletion, currency management, repayment controls, reports, and audit logs.",
    "detailTitle": "Premium Loan & Banking Website",
    "detailDescription": "A premium ready-made loan and banking website UI package designed for a professional customer experience across desktop and mobile. The customer side includes a banking-style account dashboard, loan application flow, loan/payment history, balances, and responsive mobile screens; the admin side includes application review, approval/rejection, manual funding/disbursement, debit/credit account adjustments, customer management, messaging, currency controls, repayment management, reports, audit logs, suspension, and deletion controls. The manual funding and currency features are website functionality and must be configured and operated in accordance with the applicable financial, lending, KYC/AML, consumer-protection, and payment requirements for the launch jurisdiction.",
    "features": [
      "Premium banking/loan landing page",
      "Mobile-responsive customer account",
      "Loan application system UI",
      "Customer dashboard",
      "Loan and payment history",
      "Admin dashboard with approval and rejection controls",
      "Manual funding and debit/credit account adjustments",
      "Customer management, suspension, and deletion controls",
      "Admin messaging and notifications",
      "Currency and repayment management",
      "Reports and audit logs"
    ]
  },
  "cars": {
    "id": "cars",
    "salesCount": 238,
    "title": "Car Sales Website",
    "price": 140000,
    "oldPrice": 200000,
    "minDeposit": 70000,
    "logo": "assets/car-sales.svg",
    "cover": "assets/product-covers/cars-website-main.jpg",
    "tag": "Vehicle marketplace",
    "category": "Car Sales Website",
    "description": "A vehicle dealership website to showcase cars, publish listing details, receive buyer enquiries, and manage inventory through an admin dashboard. The customer checkout can show wire transfer, Cash App, and PayPal payment options when configured by the site owner.",
    "detailTitle": "Car Sales Website with Admin Dashboard",
    "detailDescription": "A professional car dealership website for displaying vehicle photos, specifications, prices, and availability. Includes buyer enquiry and order flows, a live-chat contact entry point, and an admin dashboard concept for managing vehicle listings and site content. The customer checkout can display wire transfer, Cash App, and PayPal payment options when configured by the site owner.",
    "features": [
      "Vehicle listings with photos and specifications",
      "Search and browse inventory",
      "Buyer enquiry and order flow",
      "Live-chat/contact entry point",
      "Admin dashboard for listings and content",
      "Responsive layout and checkout-ready structure"
    ]
  },
  "tracking": {
    "id": "tracking",
    "salesCount": 119,
    "title": "Parcel & Delivery Tracking Website",
    "price": 100000,
    "oldPrice": 150000,
    "minDeposit": 50000,
    "logo": "assets/tracking-website.svg",
    "cover": "assets/product-covers/tracking-website-main.jpg",
    "tag": "Tracking platform",
    "category": "Tracking Website",
    "description": "A delivery-tracking website concept where customers can enter a tracking reference and view shipment status, with an admin area for managing tracking records.",
    "detailTitle": "Parcel & Delivery Tracking Website",
    "detailDescription": "A professional tracking website foundation for courier, logistics, and delivery businesses. Customers can enter a tracking number and view shipment updates, while an admin dashboard can be used to manage tracking records and delivery information. Live carrier integrations depend on the chosen provider and setup.",
    "features": [
      "Tracking-number search interface",
      "Shipment status and delivery updates",
      "Admin area for managing tracking records",
      "Customer-facing tracking page",
      "Branding and content customization",
      "Mobile-friendly design"
    ]
  },
  "clothing": {
    "id": "clothing",
    "salesCount": 386,
    "title": "Clothing & Online Store",
    "price": 157000,
    "oldPrice": 300000,
    "minDeposit": 80000,
    "logo": "assets/clothing-store.svg",
    "cover": "assets/product-covers/clothing-website-main.jpg",
    "tag": "E-commerce store",
    "category": "Online Store",
    "description": "A polished online shop for clothing and products with product collections, shopping cart, checkout flow, and tools to manage the storefront. Wire transfer, Cash App, and PayPal payment options can be shown in the customer checkout, subject to the site owner’s payment setup.",
    "detailTitle": "Clothing & Online Store",
    "detailDescription": "A professional e-commerce storefront for clothing, accessories, and physical products. Showcase product photos, descriptions, sizes, colors, and prices with a cart and checkout flow. Admin tools and payment-provider configuration can be included according to the final scope. The customer checkout can display wire transfer, Cash App, and PayPal payment instructions, subject to the business owner configuring those payment methods.",
    "features": [
      "Product catalog with photos and variants",
      "Collections, sizes, and color options",
      "Shopping cart and checkout flow",
      "Order and product management interface",
      "Store branding and promotional sections",
      "Responsive mobile and desktop layout"
    ]
  },
  "celebrity": {
    "id": "celebrity",
    "salesCount": 189,
    "title": "Custom Celebrity-Inspired Merchandise Store",
    "price": 150000,
    "oldPrice": 286000,
    "minDeposit": 75000,
    "logo": "assets/celebrity-store.svg",
    "cover": "assets/product-covers/celebrity-website-main.jpg",
    "tag": "Custom merchandise",
    "category": "Custom Merchandise Store",
    "description": "A customizable apparel and accessories storefront for original fan-inspired designs, including clothing, shoes, and bags for different styles and audiences. The customer checkout can show wire transfer, Cash App, and PayPal payment options when configured by the site owner.",
    "detailTitle": "Custom Merchandise Store",
    "detailDescription": "A stylish online store for customizable, original fan-inspired merchandise. Present apparel, shoes, bags, and accessories for different audiences, with product options, order collection, and a checkout flow. The customer checkout can display wire transfer, Cash App, and PayPal payment instructions when configured by the site owner. Use only images, names, and designs you have permission to use.",
    "features": [
      "Clothing, shoes, bags, and accessories catalog",
      "Product options and customization fields",
      "Shopping cart and order flow",
      "Checkout-ready storefront",
      "Product and order management interface",
      "Responsive design for phones and desktop"
    ]
  },
  "truck": {
    "id": "truck",
    "salesCount": 87,
    "title": "Truck Sales Website",
    "price": 160000,
    "oldPrice": 250000,
    "minDeposit": 80000,
    "logo": "assets/truck-sales.svg",
    "cover": "assets/product-covers/truck-website-main.jpg",
    "tag": "Commercial vehicles",
    "category": "Truck Sales Website",
    "description": "A professional platform for truck dealers to showcase commercial vehicles, share specifications, and receive buyer enquiries with listing management tools. Wire transfer, Cash App, and PayPal payment options can be shown in the customer checkout, subject to the site owner’s payment setup.",
    "detailTitle": "Truck Sales Website with Admin Dashboard",
    "detailDescription": "A dedicated website for truck and commercial-vehicle dealers. Display vehicle photos, capacity, specifications, prices, and availability, with search and buyer enquiry forms. An admin dashboard can manage listings and page content according to the agreed scope. The customer checkout can display wire transfer, Cash App, and PayPal payment instructions, subject to the business owner configuring those payment methods.",
    "features": [
      "Truck and commercial vehicle listings",
      "Photos, specifications, and pricing",
      "Search and browse inventory",
      "Buyer enquiry forms",
      "Admin listing and content management",
      "Responsive mobile and desktop layout"
    ]
  },
  "ecommerce": {
    "id": "ecommerce",
    "salesCount": 152,
    "title": "General E-commerce Website",
    "price": 170000,
    "oldPrice": 280000,
    "minDeposit": 85000,
    "logo": "assets/ecommerce-store.svg",
    "cover": "assets/product-covers/ecommerce-website-main.jpg",
    "tag": "Online business",
    "category": "E-commerce Website",
    "description": "A flexible online store for selling products across categories, with product pages, cart, checkout, and storefront customization. Wire transfer, Cash App, and PayPal payment options can be shown in the customer checkout, subject to the site owner’s payment setup.",
    "detailTitle": "General E-commerce Website",
    "detailDescription": "A flexible e-commerce website for businesses selling products online. Organize categories, publish product details and images, let shoppers add items to a cart, and guide them through checkout. Admin and payment-provider features depend on the selected scope. The customer checkout can display wire transfer, Cash App, and PayPal payment instructions, subject to the business owner configuring those payment methods.",
    "features": [
      "Product categories and product pages",
      "Shopping cart and checkout flow",
      "Storefront branding and content sections",
      "Order management interface",
      "Mobile and desktop responsive layout",
      "Expandable for additional store features"
    ]
  }
}
};
